Feature
El-Potato-Slayer/active-record pull request #1
Opened 2020-11-06 13:21 UTC by El-Potato-Slayer

2020-11-06 16:42 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
#### Hi @El-Potato-Slayer and @Lidya1234 :clap: :clap:
#### Well done :muscle: The project is well implemented. However, you need to fix the following :point_down: issue before this project can be approved.

**_Submit for another review after implementing the required changes_**

#### _Reviewed by Temitayo Adeleke_

2020-11-06 16:42 UTC, lekegitrepo commented on app/models/post.rb
> +end
- **_There should be validations for `body` and `title` in the Post model ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/postValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)). This implies that you need to add the columns for the title and body (you can change the post column to body or not) to the post table_**

2020-11-08 00:17 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

### Hi, Team 👋    
I see you have successfully the changes requested by the previous TSE. 

Just before you merge, make sure to update the few changes below and the comments I made on your readme file.

Update your PR title to a meaningful one:  Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-08 00:17 UTC, acushlakoncept commented on README.md
> +4. Run ```active_record```.
Did you mean `cd active_record` here? if so kindly update the readme file to update that.
Also `yarn install` should be part of the list. I couldn't proceed without running that command.

2022-11-18 08:17 UTC, merged